### ISSUE TITLE
Browser treating client.js as plain js

### ISSUE THREAD

**Issue by kylelt** [deecewan/boilerpl8#1] opened 2016-08-05 01:03 UTC
Symptons, basic `Hello Test` Message does not display
**Html Result**

```
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Starter Kit</title>
</head>
<body>
<div id="app"></div>

<script src="/dist/client.js"></script>

</body></html>
```

**Chrome console log:**
`
Navigated to http://192.168.99.100:3000/ 
`
`
client.js:1 Uncaught SyntaxError: Unexpected token <
`
The crazy ip is because im hosting it on a windoze and its running on a vm ...

**Contents of `client.js`  according to chrome:**

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Starter Kit</title>
</head>
<body>
<div id="app"></div>

<script src="/dist/client.js"></script>
</body>
</html>
```

**Comment by mockshox** [comment] 2016-09-13 14:22
Same here - webpack says the bundle is valid...

**Comment by deecewan** [comment] 2016-09-14 10:28
the bundle is building.  the issue is that nothing is listening at that particular place.  so it returns the index.

I've been working on this a bunch, as it's behind a bigger project of mine.  I didn't realise anyone was actually using this, so wasn't too worried about updates.

I'll get an update out ASAP.

**Comment by deecewan** [comment] 2016-10-16 07:05
This should be fixed, but the entire thing has changed.  Good Luck.

**Closed as completed by deecewan** 2016-10-16 07:05 UTC
